# Generated by Django 6.0.3 on 2026-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_groups_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "в ожидании"),
                    ("paid", "оплачено"),
                    ("failed", "отказано"),
                ],
                default="pending",
                max_length=20,
                verbose_name="статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="ссылка платежа"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="id сессии"),
        ),
    ]
