# Generated by Django 6.0.3 on 2026-04-18 09:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payment_status_payment_stripe_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 4, 18, 9, 14, 34, 261208, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Последнее посещение",
            ),
            preserve_default=False,
        ),
    ]
