# Generated by Django 6.0.3 on 2026-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление курса"
            ),
        ),
    ]
